// Generated by O/R mapper generator ver 1.0

#import <UIKit/UIKit.h>
#import "ORRecord.h"

@interface CategoryBase : ORRecord {
    NSString* mName;
    int mSorder;
}

@property(nonatomic,retain) NSString* name;
@property(nonatomic,assign) int sorder;

+ (BOOL)migrate;

+ (id)allocator;

// CRUD (Create/Read/Update/Delete) operations

// Create/update operations
// Note: You should use 'save' method
- (void)_insert;
- (void)_update;

// Read operations
+ (CategoryBase *)find:(int)pid;
+ (NSMutableArray *)find_cond:(NSString *)cond;
+ (dbstmt *)gen_stmt:(NSString *)cond;
+ (NSMutableArray *)find_stmt:(dbstmt *)cond;

// Delete operations
- (void)delete;
+ (void)delete_cond:(NSString *)cond;
+ (void)delete_all;

// internal functions
+ (NSString *)tableName;
- (void)_loadRow:(dbstmt *)stmt;

@end
