// Generated by O/R mapper generator ver 1.0

#import <UIKit/UIKit.h>
#import "ORRecord.h"

@interface DescLRU : ORRecord {
    NSString* mDescription;
    NSDate* mLastUse;
    int mCategory;
}

@property(nonatomic,retain) NSString* description;
@property(nonatomic,retain) NSDate* lastUse;
@property(nonatomic,assign) int category;

+ (BOOL)migrate;

+ (id)allocator;

// CRUD (Create/Read/Update/Delete) operations

// Create/update operations
// Note: You should use 'save' method
- (void)_insert;
- (void)_update;

// Read operations (Finder)
+ (DescLRU *)find:(int)pid;
//+ (DescLRU *)find_first:(NSString *)cond;

+ (NSMutableArray *)find_all:(NSString *)cond;

+ (dbstmt *)gen_stmt:(NSString *)cond;
+ (DescLRU *)find_first_stmt:(dbstmt *)cond;
+ (NSMutableArray *)find_all_stmt:(dbstmt *)cond;

// Delete operations
- (void)delete;
+ (void)delete_cond:(NSString *)cond;
+ (void)delete_all;

// internal functions
+ (NSString *)tableName;
- (void)_loadRow:(dbstmt *)stmt;

@end
