// Generated by O/R mapper generator ver 1.0

#import <UIKit/UIKit.h>
#import "ORRecord.h"

@interface TransactionBase : ORRecord {
    int mAsset;
    int mDstAsset;
    NSDate* mDate;
    int mType;
    int mCategory;
    double mValue;
    NSString* mDescription;
    NSString* mMemo;
}

@property(nonatomic,assign) int asset;
@property(nonatomic,assign) int dstAsset;
@property(nonatomic,retain) NSDate* date;
@property(nonatomic,assign) int type;
@property(nonatomic,assign) int category;
@property(nonatomic,assign) double value;
@property(nonatomic,retain) NSString* description;
@property(nonatomic,retain) NSString* memo;

+ (BOOL)migrate;

+ (id)allocator;

// CRUD (Create/Read/Update/Delete) operations

// Create/update operations
// Note: You should use 'save' method
- (void)_insert;
- (void)_update;

// Read operations (Finder)
+ (TransactionBase *)find:(int)pid;
//+ (TransactionBase *)find_first:(NSString *)cond;

+ (NSMutableArray *)find_all:(NSString *)cond;

+ (dbstmt *)gen_stmt:(NSString *)cond;
+ (TransactionBase *)find_first_stmt:(dbstmt *)cond;
+ (NSMutableArray *)find_all_stmt:(dbstmt *)cond;

// Delete operations
- (void)delete;
+ (void)delete_cond:(NSString *)cond;
+ (void)delete_all;

// internal functions
+ (NSString *)tableName;
- (void)_loadRow:(dbstmt *)stmt;

@end
