// Generated by O/R mapper generator ver 0.1(cashflow)

#import <UIKit/UIKit.h>
#import "ORRecord.h"

@interface TransactionBase : ORRecord {
    int asset;
    int dst_asset;
    NSDate* date;
    int type;
    int category;
    double value;
    NSString* description;
    NSString* memo;
}

@property(nonatomic,assign) int asset;
@property(nonatomic,assign) int dst_asset;
@property(nonatomic,retain) NSDate* date;
@property(nonatomic,assign) int type;
@property(nonatomic,assign) int category;
@property(nonatomic,assign) double value;
@property(nonatomic,retain) NSString* description;
@property(nonatomic,retain) NSString* memo;

+ (BOOL)migrate;

+ (id)allocator;

// CRUD (Create/Read/Update/Delete) operations

// Create operations
- (void)insert;

// Read operations
+ (TransactionBase *)find:(int)pid;
+ (NSMutableArray *)find_cond:(NSString *)cond;
+ (dbstmt *)gen_stmt:(NSString *)cond;
+ (NSMutableArray *)find_stmt:(dbstmt *)cond;

// Update operations
- (void)update;

// Delete operations
- (void)delete;
+ (void)delete_cond:(NSString *)cond;
+ (void)delete_all;

// internal functions
+ (NSString *)tableName;
- (void)_loadRow:(dbstmt *)stmt;

@end
