// Generated by O/R mapper generator ver 1.0

#import <UIKit/UIKit.h>
#import "ORRecord.h"

@class Transaction;

@interface TransactionBase : ORRecord {
    int mAsset;
    int mDstAsset;
    NSDate* mDate;
    int mType;
    int mCategory;
    double mValue;
    NSString* mDescription;
    NSString* mMemo;
}

@property(nonatomic,assign) int asset;
@property(nonatomic,assign) int dstAsset;
@property(nonatomic,retain) NSDate* date;
@property(nonatomic,assign) int type;
@property(nonatomic,assign) int category;
@property(nonatomic,assign) double value;
@property(nonatomic,retain) NSString* description;
@property(nonatomic,retain) NSString* memo;

+ (BOOL)migrate;

// CRUD (Create/Read/Update/Delete) operations

// Create/update operations
// Note: You should use 'save' method
- (void)_insert;
- (void)_update;

// Read operations (Finder)
+ (Transaction *)find:(int)pid;
+ (Transaction *)find_by_asset:(int)key cond:(NSString*)cond;
+ (Transaction *)find_by_asset:(int)key;
+ (Transaction *)find_by_dst_asset:(int)key cond:(NSString*)cond;
+ (Transaction *)find_by_dst_asset:(int)key;
+ (Transaction *)find_by_date:(NSDate*)key cond:(NSString*)cond;
+ (Transaction *)find_by_date:(NSDate*)key;
+ (Transaction *)find_by_type:(int)key cond:(NSString*)cond;
+ (Transaction *)find_by_type:(int)key;
+ (Transaction *)find_by_category:(int)key cond:(NSString*)cond;
+ (Transaction *)find_by_category:(int)key;
+ (Transaction *)find_by_value:(double)key cond:(NSString*)cond;
+ (Transaction *)find_by_value:(double)key;
+ (Transaction *)find_by_description:(NSString*)key cond:(NSString*)cond;
+ (Transaction *)find_by_description:(NSString*)key;
+ (Transaction *)find_by_memo:(NSString*)key cond:(NSString*)cond;
+ (Transaction *)find_by_memo:(NSString*)key;

+ (NSMutableArray *)find_all:(NSString *)cond;

+ (dbstmt *)gen_stmt:(NSString *)cond;
+ (Transaction *)find_first_stmt:(dbstmt *)stmt;
+ (NSMutableArray *)find_all_stmt:(dbstmt *)stmt;

// Delete operations
- (void)delete;
+ (void)delete_cond:(NSString *)cond;
+ (void)delete_all;

// internal functions
+ (NSString *)tableName;
- (void)_loadRow:(dbstmt *)stmt;

@end
